   
name: Docker Image CI

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Push Image to ECR
        uses: kciter/aws-ecr-action@v4
        with:
          access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }} 
          secret_access_key:  ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          account_id:  ${{ secrets.AWS_ACCOUNT_ID }} 
          repo: dashboard-client
          region: us-east-1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Update ECS Service 
        run: |
          ecsClusterName='dashboard-client'
          arn=$(aws ecs list-tasks --cluster dashboard-client --desired-status RUNNING --family dashboard-client-task | egrep "task/" | sed -E "s/.*task\/(.*)\"/\1/")
          aws ecs stop-task --cluster ${ecsClusterName} --task ${arn}
          aws ecs update-service --cluster ${ecsClusterName} --service dashboard-client-service  --task-definition dashboard-client-task --desired-count 1 --force-new-deploymen
